# 3- Manipulate Numpy Arrays

In [119]:
import numpy as np

## 3.1 Copy Numpy Array "="

We can easyly copy the an numpy array with equal operator

In [120]:
my_np_array_1= np.array([-45, -31, -12, 0, 2, 25, 51, 99])

my_np_array_replicated =my_np_array_1

my_np_array_replicated

array([-45, -31, -12,   0,   2,  25,  51,  99])

# 3.2 "is", "==" and Id()

"is" operator is to test whether these two references my_np_array_replicated and my_np_array_1 refer to be the same object in the memory

to test with " ==" if every operator is the same in the elements

Anotherway to test whether these two references my_np_array_replicated and my_np_array_1 refer to be the same object in the memory 

In [121]:
# 3.2.1 Example is operator
my_np_array_replicated is my_np_array_1

True

In [122]:
# 3.2.2 Example to test with " ==" if every operator is the same in the elements

my_np_array_replicated == my_np_array_1

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [123]:
#Example id operator

if (id(my_np_array_1) == id(my_np_array_replicated)):
    print (id(my_np_array_replicated))

4636984864


## 3.3. Changing a capied array's element

In a replicated array if one of the elements value is changed then the element also is changed in the orginal array

In [124]:
#Example 3.3.1 my_np_array_replicated[3]=999
my_np_array_replicated

array([-45, -31, -12,   0,   2,  25,  51,  99])

In [125]:
my_np_array_1

array([-45, -31, -12,   0,   2,  25,  51,  99])

In [126]:
#Example 3.3.2 id test
if (id(my_np_array_1) == id(my_np_array_replicated)):
    print (id(my_np_array_replicated))

4636984864


## 3.4 Left Blank

## 3.5 Array Attributes
Number of dimensions
shape
size (number of elements)
data type for elements
item size for each element within an array
type (for the array; not for elements within array)

In [127]:
a = np.array(np.arange(24).reshape(2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [128]:
a.ndim

3

In [129]:
a.shape

(2, 3, 4)

In [130]:
a.size

24

In [131]:
type(a)

numpy.ndarray

In [132]:
#a data type
a.dtype

dtype('int64')

## 3.6 Adding and removing elements

In [133]:
#append functino ()

a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## 3.6.1 numpy.append()
Numpy append funciton is different then list appemnd funciton 

Recall that if a was a pyhton list see (my-python-notebooksfrom 0 to 100) adding an element in a list would be e.g. a.append([9,9,9,9]), Howevr if you try the same thing for numpy array you would get the following error below:

    AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [134]:
# Example 3.6.1.1
b = np.append(a, [9,9,9,9])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,  9,  9,  9,  9])

In [135]:
# Example 3.6.1.2
b.shape

(28,)

In [136]:
# Example 3.6.1.3
# while you are using reshape function in numpy: the matix should be provided as  a tuple
b.reshape( (7,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 9,  9,  9,  9]])

In [137]:
# Example 3.6.1.4
#observe the a 
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [138]:
# Example 3.6.1.5
#since b and a is different numpy arrays,: recall taht we created b while using a as a resource
#see a is still the same since b is a different numpy array
a.shape

(2, 3, 4)

In [139]:
# Example 3.6.1.6
# we can merge these np arrays as a new np array
c = np.array(np.arange(24).reshape(2,3,4))*100+7
c.shape

(2, 3, 4)

In [140]:
# Example 3.6.1.7
c

array([[[   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [141]:
# Example 3.6.1.8
#merge along the axis = 0
merged_numy_arrays_axis0 = np.append(a,c, axis=0)
merged_numy_arrays_axis0

array([[[   0,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]],

       [[   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [142]:
# Example 3.6.1.9
merged_numy_arrays_axis0.shape

(4, 3, 4)

In [143]:
# Example 3.6.1.9
#merge along the axis = 1
merged_numy_arrays_axis1 = np.append(a,c, axis=1)
merged_numy_arrays_axis1

array([[[   0,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11],
        [   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23],
        [1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [144]:
# Example 3.6.1.10
merged_numy_arrays_axis1.shape

(2, 6, 4)

In [145]:
# Example 3.6.1.11
#merge along the axis = 2
merged_numy_arrays_axis2 = np.append(a,c, axis=2)
merged_numy_arrays_axis2

array([[[   0,    1,    2,    3,    7,  107,  207,  307],
        [   4,    5,    6,    7,  407,  507,  607,  707],
        [   8,    9,   10,   11,  807,  907, 1007, 1107]],

       [[  12,   13,   14,   15, 1207, 1307, 1407, 1507],
        [  16,   17,   18,   19, 1607, 1707, 1807, 1907],
        [  20,   21,   22,   23, 2007, 2107, 2207, 2307]]])

In [146]:
# Example 3.6.12
merged_numy_arrays_axis2.shape

(2, 3, 8)

## 3.7 insert ()

It's usually a good idea to have a look at the numpy documentation, regarding the obj parameter of insert funciton, you might think thet the information in the values parameter will be inserted within the array.

Similar to using index slices in array selection, however usually the insert means to place something within an existing data structure. 

The NumPy's insert function creates a new array with new data. Notice that the array input is not changed. See the example below

In [147]:
## 3.7.1 Example Insert function
#Recall the C
c

array([[[   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [148]:
## 3.7.2 Example Insert function
#np.insert(c,"location" =0 , "value="444,axis=0)
new_insert_numpy_0 = np.insert(c,0,444,axis=0)
new_insert_numpy_0 

array([[[ 444,  444,  444,  444],
        [ 444,  444,  444,  444],
        [ 444,  444,  444,  444]],

       [[   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [149]:
## 3.7.3 Example Insert function
new_insert_numpy_1 = np.insert(c,0,444,axis=0)
new_insert_numpy_1 

array([[[ 444,  444,  444,  444],
        [ 444,  444,  444,  444],
        [ 444,  444,  444,  444]],

       [[   7,  107,  207,  307],
        [ 407,  507,  607,  707],
        [ 807,  907, 1007, 1107]],

       [[1207, 1307, 1407, 1507],
        [1607, 1707, 1807, 1907],
        [2007, 2107, 2207, 2307]]])

In [150]:
## 3.7.4 Example Insert function
new_d_array = np.empty(c.shape)
new_d_array

array([[[0.0000e+000, 4.9407e-322, 9.8813e-322, 1.4822e-321],
        [1.9763e-321, 2.4703e-321, 2.9644e-321, 3.4585e-321],
        [3.9525e-321, 4.4466e-321, 4.9407e-321, 5.4347e-321]],

       [[5.9288e-321, 6.4229e-321, 6.9169e-321, 7.4110e-321],
        [7.9051e-321, 8.3991e-321, 8.8932e-321, 9.3872e-321],
        [9.8813e-321, 1.0375e-320, 1.0869e-320, 1.1364e-320]]])

## 3.8 np.copyto()

In [151]:
## 3.8.1 Example Insert function
np.copyto(new_d_array,c)
new_d_array

array([[[   7.,  107.,  207.,  307.],
        [ 407.,  507.,  607.,  707.],
        [ 807.,  907., 1007., 1107.]],

       [[1207., 1307., 1407., 1507.],
        [1607., 1707., 1807., 1907.],
        [2007., 2107., 2207., 2307.]]])

## 3.9 np.delete()

In [152]:
## 3.9.1 Example Insert function
np.delete(new_d_array,1,axis=0)

array([[[   7.,  107.,  207.,  307.],
        [ 407.,  507.,  607.,  707.],
        [ 807.,  907., 1007., 1107.]]])

In [153]:
#observe the new_d_array parameter is still the same
new_d_array

array([[[   7.,  107.,  207.,  307.],
        [ 407.,  507.,  607.,  707.],
        [ 807.,  907., 1007., 1107.]],

       [[1207., 1307., 1407., 1507.],
        [1607., 1707., 1807., 1907.],
        [2007., 2107., 2207., 2307.]]])

## 3.10 Join and Split

- concatenate
- stack
- split

In [154]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [155]:
b

array([[5, 6]])

In [156]:
a_b_together = np.concatenate((a,b), axis=0)
a_b_together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
a_b_together.shape

(3, 2)

In [158]:
a_b_together[1,1] = 555

In [159]:
a_b_together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [160]:
#observe a is still same after the 555 assignment
a

array([[1, 2],
       [3, 4]])

In [161]:
#observe b is still same after the 555 assignment
b

array([[5, 6]])

In [162]:
#lets creat a new np arry called c
c = np.array([[1,2],[3,4]])*10+1
c

array([[11, 21],
       [31, 41]])

In [163]:
#lets merge them on axis=1

np.concatenate((c,a),axis=1)

array([[11, 21,  1,  2],
       [31, 41,  3,  4]])

## 3.11 Stack ()
to be able to explain lets create a list of five arrays, each of which has three rows and four columns. 

In these rows and columns, the elements are populated with normally distributed random numbers. Here we create the array, starting with np.0. Five by three by four, so it's 15 times four, you will have 60 elements. Now we'll use a control statement, a for loop, and assign a random value with a mean of three, and a standard deviation of four, to each element within the array.

Here we see, we have five two-dimensional arrays, each which contains three rows, and each of which contains four columns. This snippet constructs three variables, three stacks, with names Stack0, Stack1, and Stack2. The difference among these, is that the stacking takes place along axis=0, axis=1, and axis=2. Let's examine each of these variables. Stack0, contains all of the elements in the original array.


In [164]:
my_arr = np.zeros((5,3,4))
for n in range(5):
    my_arr[n] = np.random.randn(3,4)
my_arr

array([[[ 0.21249666, -1.24649414, -0.84385791, -0.87570998],
        [ 0.24079929, -0.56039296,  1.10539285, -1.19414436],
        [-1.96736069, -0.15750028,  0.59198721, -0.25995198]],

       [[-0.05093031,  0.43136016,  0.06906312, -0.4729625 ],
        [ 0.63738353,  1.74860612, -0.71183562,  0.20867779],
        [-0.28223791,  0.7507659 ,  0.32136353, -1.13264415]],

       [[-0.13186487, -0.95190209, -1.78519206,  1.24681227],
        [-1.10109429,  1.02294222,  0.93052695,  0.10911138],
        [ 0.15056369,  0.72124631,  0.99256927, -1.14255489]],

       [[-1.39911027,  1.8784721 ,  2.08375407, -0.77265912],
        [ 2.12360609, -1.61229158,  2.29270475,  0.10304787],
        [-1.37673711,  0.53518715, -2.17539556,  0.86335757]],

       [[ 0.17555575,  0.23527445,  0.0945386 ,  0.66791525],
        [ 0.45838548, -1.57669683, -0.08249042, -1.0301924 ],
        [ 1.0331703 , -0.30675064, -0.8015047 ,  0.62333212]]])

In [165]:
my_stack0 = np.stack(my_arr,axis=0)
my_stack1 = np.stack(my_arr,axis=1)
my_stack2 = np.stack(my_arr,axis=2)

In [166]:
#my_stack0 contains all the element sin the original array
my_stack0

array([[[ 0.21249666, -1.24649414, -0.84385791, -0.87570998],
        [ 0.24079929, -0.56039296,  1.10539285, -1.19414436],
        [-1.96736069, -0.15750028,  0.59198721, -0.25995198]],

       [[-0.05093031,  0.43136016,  0.06906312, -0.4729625 ],
        [ 0.63738353,  1.74860612, -0.71183562,  0.20867779],
        [-0.28223791,  0.7507659 ,  0.32136353, -1.13264415]],

       [[-0.13186487, -0.95190209, -1.78519206,  1.24681227],
        [-1.10109429,  1.02294222,  0.93052695,  0.10911138],
        [ 0.15056369,  0.72124631,  0.99256927, -1.14255489]],

       [[-1.39911027,  1.8784721 ,  2.08375407, -0.77265912],
        [ 2.12360609, -1.61229158,  2.29270475,  0.10304787],
        [-1.37673711,  0.53518715, -2.17539556,  0.86335757]],

       [[ 0.17555575,  0.23527445,  0.0945386 ,  0.66791525],
        [ 0.45838548, -1.57669683, -0.08249042, -1.0301924 ],
        [ 1.0331703 , -0.30675064, -0.8015047 ,  0.62333212]]])

In [167]:
# Contains first 3x4 elements
my_stack1

array([[[ 0.21249666, -1.24649414, -0.84385791, -0.87570998],
        [-0.05093031,  0.43136016,  0.06906312, -0.4729625 ],
        [-0.13186487, -0.95190209, -1.78519206,  1.24681227],
        [-1.39911027,  1.8784721 ,  2.08375407, -0.77265912],
        [ 0.17555575,  0.23527445,  0.0945386 ,  0.66791525]],

       [[ 0.24079929, -0.56039296,  1.10539285, -1.19414436],
        [ 0.63738353,  1.74860612, -0.71183562,  0.20867779],
        [-1.10109429,  1.02294222,  0.93052695,  0.10911138],
        [ 2.12360609, -1.61229158,  2.29270475,  0.10304787],
        [ 0.45838548, -1.57669683, -0.08249042, -1.0301924 ]],

       [[-1.96736069, -0.15750028,  0.59198721, -0.25995198],
        [-0.28223791,  0.7507659 ,  0.32136353, -1.13264415],
        [ 0.15056369,  0.72124631,  0.99256927, -1.14255489],
        [-1.37673711,  0.53518715, -2.17539556,  0.86335757],
        [ 1.0331703 , -0.30675064, -0.8015047 ,  0.62333212]]])

In [168]:
#contains second 3x4 elements
my_stack2

array([[[ 0.21249666, -0.05093031, -0.13186487, -1.39911027,
          0.17555575],
        [-1.24649414,  0.43136016, -0.95190209,  1.8784721 ,
          0.23527445],
        [-0.84385791,  0.06906312, -1.78519206,  2.08375407,
          0.0945386 ],
        [-0.87570998, -0.4729625 ,  1.24681227, -0.77265912,
          0.66791525]],

       [[ 0.24079929,  0.63738353, -1.10109429,  2.12360609,
          0.45838548],
        [-0.56039296,  1.74860612,  1.02294222, -1.61229158,
         -1.57669683],
        [ 1.10539285, -0.71183562,  0.93052695,  2.29270475,
         -0.08249042],
        [-1.19414436,  0.20867779,  0.10911138,  0.10304787,
         -1.0301924 ]],

       [[-1.96736069, -0.28223791,  0.15056369, -1.37673711,
          1.0331703 ],
        [-0.15750028,  0.7507659 ,  0.72124631,  0.53518715,
         -0.30675064],
        [ 0.59198721,  0.32136353,  0.99256927, -2.17539556,
         -0.8015047 ],
        [-0.25995198, -1.13264415, -1.14255489,  0.86335757,
          0

## 3.12 Split ()

http://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html

NumPy Split function, separates arrays into two or more sub-arrays. 

If the parameter in the Split function is less than one, the function returns an error. If the parameter is equal to one, in this case, we're using the split function, with our temp array, the parameter equal to one, it returns the original array. Now we'll re-use the random numbers in our Stack variable to illustrate the split function. Recall, that before splitting, the stack is a three-dimensional array, with 60 elements. We can illustrate this, by showing the shape of before split.

Which is equal to the variable Stack0. The first thing that we'll do, is create a new variable, s0, using NumPy's Split function. We'll take our before split, which is equal to Stack0, and separate it into five new arrays, along the axis equal to zero. We can display this result, and it looks very similar to before split and Stack0. Let's look at the type for s0.

It's a NumPy list. Let's look at the components within s0. Each component within s0 is a two-dimensional array, with three rows, and four columns. Let's look at the shape of this, and so we have shape, and the shape is one two-dimensional array, which has three rows, and four columns. Let's use Split again, and this time, we'll split along axis=1, and we'll call the resulting variable s1.

Let's do the same thing one more time. We'll create another variable, s2, where you split, again, we'll use the before-split variable, we'll want to create four new arrays, along axis=2. And here we see the result displayed. In this video, we examined techniques for joining and splitting arrays, in particular, we looked at concatenation, and splitting.

In [169]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [170]:
before_split = my_stack0
before_split.shape

(5, 3, 4)

In [171]:
s0=np.split (before_split, 5, axis=0)
s0

[array([[[ 0.21249666, -1.24649414, -0.84385791, -0.87570998],
         [ 0.24079929, -0.56039296,  1.10539285, -1.19414436],
         [-1.96736069, -0.15750028,  0.59198721, -0.25995198]]]),
 array([[[-0.05093031,  0.43136016,  0.06906312, -0.4729625 ],
         [ 0.63738353,  1.74860612, -0.71183562,  0.20867779],
         [-0.28223791,  0.7507659 ,  0.32136353, -1.13264415]]]),
 array([[[-0.13186487, -0.95190209, -1.78519206,  1.24681227],
         [-1.10109429,  1.02294222,  0.93052695,  0.10911138],
         [ 0.15056369,  0.72124631,  0.99256927, -1.14255489]]]),
 array([[[-1.39911027,  1.8784721 ,  2.08375407, -0.77265912],
         [ 2.12360609, -1.61229158,  2.29270475,  0.10304787],
         [-1.37673711,  0.53518715, -2.17539556,  0.86335757]]]),
 array([[[ 0.17555575,  0.23527445,  0.0945386 ,  0.66791525],
         [ 0.45838548, -1.57669683, -0.08249042, -1.0301924 ],
         [ 1.0331703 , -0.30675064, -0.8015047 ,  0.62333212]]])]

In [172]:
type(s0)

list

In [173]:
s0[1]

array([[[-0.05093031,  0.43136016,  0.06906312, -0.4729625 ],
        [ 0.63738353,  1.74860612, -0.71183562,  0.20867779],
        [-0.28223791,  0.7507659 ,  0.32136353, -1.13264415]]])

In [174]:
s0[1].shape

(1, 3, 4)

In [175]:
#do the same for s1 and s2

## 3.13 np.reshape()
http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape



In [176]:
my_new_array = np.array(np.arange(24))
my_new_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [177]:
my_new_array = my_new_array.reshape(3,8)
my_new_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

## 3.13 np.ravel()
returns one dimentional array

In [178]:
my_new_ravel_array = my_new_array.ravel()
my_new_ravel_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 3.14 np.flat
enables to iterates elemnt of the numpy array this is very useful in the for loop

In [179]:
for i in my_new_array.flat:
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


## 3.15 np.fliplr (my_array )
-flip left right enable to reverse the rows and columns. Let's examine an example 
there are some more similar functions like e.g. fliplr is a flipud or flip up down.

In [180]:
my_new_array_3_8 = my_new_array.reshape(3,8)
my_new_array_3_8


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [181]:
np.fliplr(my_new_array_3_8)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [182]:
#If we use the flip left right function on my two by three by four array, 
#the results might be slightly counterintuitive.
my_new_array_2_3_8 = np.arange(48).reshape(2,3,8)
my_new_array_2_3_8

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [183]:
#the arrays are stacked top to bottom.
#the function says left to right, but the displayed presentation is bottom to top.
np.fliplr(my_new_array_2_3_8)

array([[[16, 17, 18, 19, 20, 21, 22, 23],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[40, 41, 42, 43, 44, 45, 46, 47],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [24, 25, 26, 27, 28, 29, 30, 31]]])

## 3.16 np.roll(my_array)

The next function is to examine is roll which is self-explanatory rolls the array (see the exmaple below) five positions or munis five positions.

In [184]:
my_new_arr =np.arange(20)
my_new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [185]:
my_rolled_arr_clockwise = np.roll(my_new_arr,5)
my_rolled_arr_clockwise

array([15, 16, 17, 18, 19,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14])

In [186]:
my_rolled_arr_negative = np.roll(my_new_arr,-5)
my_rolled_arr_negative

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  0,  1,
        2,  3,  4])

## 3.17 np.rot90(my_array)

ROT 90 or rotate 90 degrees enable to rotate the rows and columns clockwise 90 degrees. Furthermore, the Rotate 90 function has a parameter K which allows us to rotate arrays in a negative direction. For instance, if k=-2 it means two times 90 degrees rotation to negative direction

In [187]:
my_array_3_time_8 = np.arange(24).reshape(3,8)
my_array_3_time_8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [188]:
np.rot90(my_array_3_time_8)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [189]:
np.rot90(my_array_3_time_8,k=-1)

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

In [190]:
np.rot90(my_array_3_time_8,k=-1) # if k=-2 it means two times 90 degrees rotation to negative direction

array([[16,  8,  0],
       [17,  9,  1],
       [18, 10,  2],
       [19, 11,  3],
       [20, 12,  4],
       [21, 13,  5],
       [22, 14,  6],
       [23, 15,  7]])

## 3.18 np.transpose, swapaxes and rollaxes

For sure the NumPy data structure supports the transpose operation.

For a matrix A, which has elements row=I column=J, the element I x J, is transposed into the element A' J x I.


As a summary of swapping and transpose and rollaxis 
    -use np.transpose to permute all the axis at once. 
    -use np.swapaxes to swap any two axes. 
    -use np.rollaxis to rotate over the axes. 
    
    

In [191]:
my_array = np.arange(24)


In [192]:
#my_array is a one dimensional array, it's transpose is equal to itself.

np.transpose(my_array)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [193]:
#recall that reshape function takes a tupple
my_array_3_8 = my_array.reshape((3,8))
my_array_3_8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [194]:
#see that the rows and columns are exchanged.
np.transpose(my_array_3_8)

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [195]:
my_array_2_3_4 = my_array.reshape((2,3,4))
my_array_2_3_4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [196]:
np.transpose(my_array_2_3_4, axes=(0,2,1))

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

## 3.18.1 np.swapaxes(my_array) 
see the example below which is self explanatory

In [197]:
np.swapaxes(my_array_2_3_4, 1, 0)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

## 3.18.2 np.rollaxes(my_array)
see the example below which is self explanatory

In [198]:
np.rollaxis(my_array_2_3_4, 0, 2)

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

# 3.19 Tiling Arrays

### tile
according to the documentation at this URL : http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html#numpy.tile

Construct an array by repeating A the number of times given by reps.

If reps has length d, the result will have dimension of max(d, A.ndim).

If A.ndim < d, A is promoted to be d-dimensional by prepending new axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication, or shape (1, 1, 3) for 3-D replication. If this is not the desired behavior, promote A to d-dimensions manually before calling this function.

If A.ndim > d, reps is promoted to A.ndim by pre-pending 1’s to it. Thus for an A of shape (2, 3, 4, 5), a reps of (2, 2) is treated as (1, 1, 2, 2).

In [199]:
my_array = np.array(np.arange(12))
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [200]:
np.tile(my_array, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [201]:
np.tile(my_array, 3).reshape((3,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [202]:
my_array_2 = np.array(np.arange(7))
my_array_2

array([0, 1, 2, 3, 4, 5, 6])

In [203]:
my_tile_1 = np.tile(my_array_2, (3, 1))
my_tile_1

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [204]:
my_tile_2 = np.tile(tile_1, (2,2))
my_tile_2

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

In [205]:
my_tile_3 = np.tile(my_tile_2, (3,1))
my_tile_3

array([[0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6]])

## 3.20 repeat()
repeats each array e.g. 3 times, see the example below

In [206]:
np.repeat(my_array_2, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [207]:
my_array_repeated = np.array(np.arange(24)).reshape(2,3,4)
my_array_repeated

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [208]:
np.repeat(my_array_repeated, 2, axis=0)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])