# 1 Numpy Indexing


## 1.1 One dimentional arrays

In [18]:
import numpy as np


In [19]:
my_vector = np.array([1,2,3,4,5])
my_vector

array([1, 2, 3, 4, 5])

In [20]:
#Example 1.1 accesing element with an index number
my_vector[0]

1

In [21]:
#Example 1.2 accesing element with an negative index number
my_vector[-1]

5

In [22]:
#Example 1.3 accesing element with an index number which calculated with mathematical operations
my_vector[100//50] 

3

In [23]:
#Example 1.4 you canuse some functions as well
my_vector[100//(10*my_vector.size)] 

3

In [24]:
#Example 1.5 ssigning a new value
my_vector[0] = 100
my_vector

array([100,   2,   3,   4,   5])

## 1.2 Two-dimentional arrays

## 1.2.1 shape()

In [36]:
#1.2.1 Example creating two dimentional numpy arrays 
my_2_dim_arr = np.arange(35)
my_2_dim_arr.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [38]:
#1.2.1 Example accessing a row 
my_array[2]

array([10, 11, 12, 13, 14])

In [49]:
#1.2.1 Example accessing a certain element 
row=4,
column=3
my_array[row,column]

array([23])

## 1.2.2 creating three dimentional arrays

The major difference is that it's displayed as a record.array. 
The reason that this is important, is that I can use the person_record_array, and now I can select the first element and instead of using an index like height or weight, that I used above, I'm going to use an attribute. And in particular I use the attribute age for this example. This is telling us that if we look at this array, where the first record is Delta, the person Delta has an age 34, this is what's displayed.



In [52]:
my_three_dim_array = np.arange(30)
my_three_dim_array.shape = (3,5,2)
my_three_dim_array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [57]:
#Access the second two dimentional array
my_three_dim_array [1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [58]:
#Access a row of the second two dimentional array
my_three_dim_array [1,4]

array([18, 19])

In [60]:
#Access the last element of the second two dimentional array
my_three_dim_array [1,4,1]

19

# 1.3. Blooen Mask

There are two ways to achieve the same results:
•	first to use python's logical operators, and 
•	the second used numpy's logical and function.

These two methods are very similar. The reason that you might choose to use numpy's logical functions is that when you're dealing with very large arrays, numpy's functions will probably be more efficient.


In [103]:
#create an numpy array from python list

my_vector = np.array([-15, -4, 0, 2, 25, 35, 105])
my_vector

array([-15,  -4,   0,   2,  25,  35, 105])

In [104]:
my_zero_mode_five_vector = (my_vector%5 == 0)

my_zero_mode_five_vector #created an array of Boolean values whether the elemen is divisible by 5 or not

array([ True, False,  True, False,  True,  True,  True])

In [105]:
# we can use our my_zero_mode_five_vector use it as index to create a sub array
my_sub_array = my_vector[my_zero_mode_five_vector]
my_sub_array

array([-15,   0,  25,  35, 105])

In [106]:
#use the my_sub_array in my_sub_array itself to select the values greater than zero
#notice the the variables are not changes just filtered
my_sub_array[ my_sub_array>0 ] 

array([ 25,  35, 105])

## 1.3.1 Combined_mask

In [107]:
my_vector

array([-15,  -4,   0,   2,  25,  35, 105])

In [108]:
my_mod_test = 0 == my_vector%5
my_mod_test

array([ True, False,  True, False,  True,  True,  True])

In [109]:
my_pozitif_test = my_vector >= 0
my_pozitif_test

array([False, False,  True,  True,  True,  True,  True])

In [110]:
my_combined_test= np.logical_and(my_pozitif_test,my_mod_test)
my_combined_test

array([False, False,  True, False,  True,  True,  True])

In [111]:
#We can use combined-mask to index our original vector
my_vector[my_combined_test]

array([  0,  25,  35, 105])

## 1.4. Structured and Record Arrays

In [118]:
person_data_def = [("name","S6"),("height","f8"),("weight","f8"), ("age","int8")]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'int8')]

In [123]:
my_people_array = np.zeros((4,),dtype=person_data_def)
my_people_array

array([(b'', 0., 0., 0), (b'', 0., 0., 0), (b'', 0., 0., 0),
       (b'', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [131]:
my_people_array[2] = ("Caner",11, 9, 35)
my_people_array[1] = ("Mary", 73, 205, 34)
my_people_array

array([(b'',  0.,   0.,  0), (b'Mary', 73., 205., 34),
       (b'Caner', 11.,   9., 35), (b'',  0.,   0.,  0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [132]:
my_people_array[0:]

array([(b'',  0.,   0.,  0), (b'Mary', 73., 205., 34),
       (b'Caner', 11.,   9., 35), (b'',  0.,   0.,  0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [135]:
ages= my_people_array["age"]
ages

array([ 0, 34, 35,  0], dtype=int8)

## 1.4.1 Multi-dimensional Structured Arrays


In [138]:
my_people_big_multi_dim_array = np.zeros((4,3,2), dtype = person_data_def)
my_people_big_multi_dim_array

array([[[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]],

       [[(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)],
        [(b'', 0., 0., 0), (b'', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [150]:
my_people_big_multi_dim_array[3,2,1] = ("Mike",180,95,33)
my_people_big_multi_dim_array[3,1,1] = ("Sara",180,95,33)
my_people_big_multi_dim_array[2,1,0] = ("RL",120,35,3)


my_people_big_multi_dim_array[0,0,0] = ("Dude",100,90,30)

my_people_big_multi_dim_array

array([[[(b'Dude', 100., 90., 30), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'RL', 120., 35.,  3), (b'',   0.,  0.,  0)],
        [(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)]],

       [[(b'',   0.,  0.,  0), (b'',   0.,  0.,  0)],
        [(b'RL', 180., 95., 33), (b'Sara', 180., 95., 33)],
        [(b'',   0.,  0.,  0), (b'Mike', 180., 95., 33)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [151]:
my_people_big_multi_dim_array['height']

array([[[100.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [120.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [180., 180.],
        [  0., 180.]]])

In [153]:
my_people_big_multi_dim_array[['height', 'weight']]

array([[[(100., 90.), (  0.,  0.)],
        [(  0.,  0.), (  0.,  0.)],
        [(  0.,  0.), (  0.,  0.)]],

       [[(  0.,  0.), (  0.,  0.)],
        [(  0.,  0.), (  0.,  0.)],
        [(  0.,  0.), (  0.,  0.)]],

       [[(  0.,  0.), (  0.,  0.)],
        [(120., 35.), (  0.,  0.)],
        [(  0.,  0.), (  0.,  0.)]],

       [[(  0.,  0.), (  0.,  0.)],
        [(180., 95.), (180., 95.)],
        [(  0.,  0.), (180., 95.)]]],
      dtype=[('height', '<f8'), ('weight', '<f8')])

## 1.4.2 Creating Record Arrays

In [160]:
my_people_record_array = np.rec.array([('Delta', 73, 205, 34),('Alpha', 65, 112, 23)],dtype=person_data_def)
my_people_record_array

rec.array([(b'Delta', 73., 205., 34), (b'Alpha', 65., 112., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', 'i1')])

In [161]:
my_people_record_array[0].age

34