# What is Numpy and Why ?



In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.15.2


## 1.1 Creating Numpy array form a list 

A simplest way to create a numpy array is using a list, you can find an example below wher eyou creat a list first then an np.array

observe that the separator between elements within a data structure is a comma,like every data structure within Python.

### 1.1.1 Example Creating Numpy array form a list 



In [3]:
# 1.1.1 Example Creating Numpy array form a list 

my_list = [1,2,3,4,5]

my_numpy_array_from_a_list = np.array(my_list)

my_numpy_array_from_a_list

array([1, 2, 3, 4, 5])

## 1.2 Creating Numpy array form a tuple 

A simplest way to create a numpy array is using a list, you can find an example below wher eyou creat a list first then an np.array

observe that the separator between elements within a data structure is a comma,like every data structure within Python.

### 1.1.2 Example Creating Numpy array form a tuple 



In [4]:
# 1.1.1 Example Creating Numpy array form a list 

my_tuple = (1,2,3,4,5)

my_numpy_array_from_a_tuple = np.array(my_tuple)

my_numpy_array_from_a_tuple

array([1, 2, 3, 4, 5])

### 1.1.3 Example Numpy promotes the numbers


In [5]:
# 1.1.3.A Example Numpy array promotes float numbers

my_tuple2 = (1,2.5,3,4.2,5)

my_numpy_array_from_a_tuple2 = np.array(my_tuple2)

my_numpy_array_from_a_tuple2

array([1. , 2.5, 3. , 4.2, 5. ])

In [6]:
# 1.1.3.B Example Numpy array promotes complex numbers
my_tuple3 = (1,2+3j,3j)

my_numpy_array_from_a_tuple3 = np.array(my_tuple3)

my_numpy_array_from_a_tuple3

array([1.+0.j, 2.+3.j, 0.+3.j])

### Difference between python and numpy data structures

In [7]:
my_tuple * 6 # In python asterix ( *) operator repeats each element 6 times

(1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5)

In [8]:
np.array(my_tuple) * 6 #numpy enables the matematical operations and simplifies the life

array([ 6, 12, 18, 24, 30])

## 1.2 Numpy.arrange() Function

The python arange function is a very basic function, and you'll find it very useful in multiple situations. In fact, arange is to NumPy as multiplication and division is to Python.


In [26]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
#Example 1.2.1
#np.arange(start_param, end_param, step_param )
np.arange(5,100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
#Example 1.2.2
#np.arange(start_param, end_param, step_param )
np.arange(5,100)/10

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7,
       1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ,
       3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3,
       4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6,
       5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9,
       7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2,
       8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5,
       9.6, 9.7, 9.8, 9.9])

In [29]:
#Example 1.2.3
#np.arange(start_param, end_param, step_param )
np.arange(5,100)/10+1000

array([1000.5, 1000.6, 1000.7, 1000.8, 1000.9, 1001. , 1001.1, 1001.2,
       1001.3, 1001.4, 1001.5, 1001.6, 1001.7, 1001.8, 1001.9, 1002. ,
       1002.1, 1002.2, 1002.3, 1002.4, 1002.5, 1002.6, 1002.7, 1002.8,
       1002.9, 1003. , 1003.1, 1003.2, 1003.3, 1003.4, 1003.5, 1003.6,
       1003.7, 1003.8, 1003.9, 1004. , 1004.1, 1004.2, 1004.3, 1004.4,
       1004.5, 1004.6, 1004.7, 1004.8, 1004.9, 1005. , 1005.1, 1005.2,
       1005.3, 1005.4, 1005.5, 1005.6, 1005.7, 1005.8, 1005.9, 1006. ,
       1006.1, 1006.2, 1006.3, 1006.4, 1006.5, 1006.6, 1006.7, 1006.8,
       1006.9, 1007. , 1007.1, 1007.2, 1007.3, 1007.4, 1007.5, 1007.6,
       1007.7, 1007.8, 1007.9, 1008. , 1008.1, 1008.2, 1008.3, 1008.4,
       1008.5, 1008.6, 1008.7, 1008.8, 1008.9, 1009. , 1009.1, 1009.2,
       1009.3, 1009.4, 1009.5, 1009.6, 1009.7, 1009.8, 1009.9])

In [30]:
#Example 1.2.4
#np.arange(start_param, end_param, step_param )
np.arange(5,100,20)

array([ 5, 25, 45, 65, 85])

In [31]:
#Example 1.2.5
#np.arange(start_param, end_param, step_param ) if you do not set a start param, python assumes it is zero
np.arange(100,step=20)

array([ 0, 20, 40, 60, 80])

## 1.3 len and size Function

In [32]:
my_numpy = np.arange(5,100,20)

if my_numpy.size == len(my_numpy):
    print (f" my_numpy.size and len(my_numpy) are equal which is {my_numpy.size}")

 my_numpy.size and len(my_numpy) are equal which is 5


## 1.4. linspace()

**linspace()** creates an array whose elements are evenly spaced over a specified interval. Calls to linspace contain between start_param and end_params parameters and evenly spaced numbers. Notice that the start and the end parameters are mandatory.

In particular,in contrast to the arange function, the value of the stop parameter is included in the created array. Furthermore,  linspace uses a closed interval such that its start and stop parameters are included in a created array whereas arange uses a half-closed or half-open interval such that its start parameter is included but its stop parameter is not included.

In [36]:
np.linspace(5,10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [40]:
#if we set the return step parameter to true.
#the results in my_linspace numpy array, it has two components. 
#The first component is an ndarray that ranges from 5 to 10. 
#And the second component is the step size.
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace[1] #prints the increment value

1.25

In this example, it is easy to determine that the step size is one and a quarter. In general, you can use the documentation and the formula that states there are num equally-spaced samples in the closed interval start stop or the half-open interval start stop, depending upon whether or not the endpoint parameter is true or false. Rather than perform this calculation yourself, you can tell linspace to return the step size using the return step parameter.

 I can access this directly by taking the variable name and accessing its second component. Notice that numpy is using zero-based indexing.

So the second component has the index equal to one. The next function that we'll examine is the zeros function. We can create a little header for ourselves by using markdown and telling ourselves that we're going to be talking about the zeros function.


## 1.5 zeros()

The next function to examine is the zeros function which creates an array that is filled with zeros.

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros((5,10)) # returns an array that is filled with floating point values.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 1.6 ones()

In [42]:
np.ones(10) #returns an array that is filled with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 1.7 ndarrays

A multi-dimensional array can be created by passing a tuple of shapes to either the ones functions or the zeros function.

## Example 1.7.1 two-dimentional ndarrays

In the example below there is an ndarray that contains five rows and four columns where each element is equal to zero as a floating point value.

The ndarray is a two-dimensional array whom each componenet within the array is a one-dimensional array that contains five elements. So we have five rows, five elements, each which contains four columns. 


In [58]:
# Example 1.7.1 ndarrays
#creates an ndarray that contains five rows and four columns 
#where each element is equal to zero as a floating point value.
np.ones((4,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Example 1.7.1 three-dimentional ndarrays

The first number, five, indicates that there are five two-dimensional arrays. 
The second number, four, tells us that we have four groups of matrices .


In [60]:
# Example 1.7.1 ndarrays
np.zeros((5,10,3)) #returns a three-dimentional ndarray

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
  

## 1.5 Data Types

In [64]:
np.zeros(10, dtype="int64")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])